<a href="https://colab.research.google.com/github/devanshu6738/Computer_Vision/blob/main/basic_cnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install opendatasets

In [2]:
import opendatasets as od
od.download("https://www.kaggle.com/datasets/salader/dogsvscats/")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: Devanshu67
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/salader/dogsvscats


100%|██████████| 1.06G/1.06G [00:30<00:00, 37.9MB/s]


In [3]:
! pip install numpy tensorflow matplotlib keras

In [4]:
cat_path="/content/dogsvscats/train/cats"
dog_path="/content/dogsvscats/train/dogs"

In [5]:
import os
len(os.listdir(cat_path)),len(os.listdir(dog_path))

(10000, 10000)

In [6]:
import cv2 as cv
img=cv.imread("/content/dogsvscats/train/cats/cat.0.jpg")
img.shape

(374, 500, 3)

In [7]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
base_dir="/content/dogsvscats/train"
data_datagen=ImageDataGenerator(rescale=1./255,validation_split=0.2)

In [8]:
train_gen=data_datagen.flow_from_directory(
    base_dir,
    target_size=(150,150),
    batch_size=50,
    class_mode='binary',
    subset='training'
)
valdation_gen=data_datagen.flow_from_directory(
    base_dir,
    target_size=(150,150),
    batch_size=50,
    class_mode='binary',
    subset='validation',
    shuffle=False
)

Found 16000 images belonging to 2 classes.
Found 4000 images belonging to 2 classes.


In [9]:
train_gen.class_indices

{'cats': 0, 'dogs': 1}

In [10]:
import keras
from keras import layers
model=keras.Sequential([
    # layer1
     layers.Conv2D(32,(3,3),activation='relu',input_shape=(150,150,3)),
     layers.MaxPooling2D(2,2),
    # layer2
     layers.Conv2D(64,(3,3),activation='relu',input_shape=(150,150,3)),
     layers.MaxPooling2D(2,2),
    # layer3
     layers.Conv2D(128,(3,3),activation='relu',input_shape=(150,150,3)),
     layers.MaxPooling2D(2,2),
    # layer4
     layers.Conv2D(128,(3,3),activation='relu',input_shape=(150,150,3)),
     layers.MaxPooling2D(2,2),

     layers.Flatten(),
     layers.Dense(512,activation='relu'),
     layers.Dense(1,activation='sigmoid')

])
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 148, 148, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 74, 74, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 72, 72, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 36, 36, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 34, 34, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 17, 17, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 15, 15, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 7, 7, 128)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 6272)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 512)            │     3,211,776 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           513 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,453,121 (13.17 MB)

 Trainable params: 3,453,121 (13.17 MB)

 Non-trainable params: 0 (0.00 B)

In [11]:
 model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [12]:
history=model.fit(train_gen,epochs=10,validation_data=valdation_gen)

Epoch 1/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 44s 105ms/step - accuracy: 0.5529 - loss: 0.6857 - val_accuracy: 0.6793 - val_loss: 0.5977
Epoch 2/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 32s 100ms/step - accuracy: 0.7129 - loss: 0.5552 - val_accuracy: 0.7565 - val_loss: 0.5081
Epoch 3/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 31s 96ms/step - accuracy: 0.7834 - loss: 0.4595 - val_accuracy: 0.7840 - val_loss: 0.4628
Epoch 4/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 30s 92ms/step - accuracy: 0.8214 - loss: 0.3950 - val_accuracy: 0.8225 - val_loss: 0.3955
Epoch 5/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 30s 93ms/step - accuracy: 0.8581 - loss: 0.3261 - val_accuracy: 0.8595 - val_loss: 0.3312
Epoch 6/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 31s 95ms/step - accuracy: 0.8833 - loss: 0.2703 - val_accuracy: 0.8550 - val_loss: 0.3444
Epoch 7/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 30s 94ms/step - accuracy: 0.9103 - loss: 0.2196 - val_accuracy: 0.8622 - val_loss: 0.3576
Epoch 8/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 31s 96ms/step - accuracy: 0.9283 - loss: 0.1744 

In [13]:
test_datagen=ImageDataGenerator(rescale=1./255)
test_dir="/content/dogsvscats/test"
test_gen=test_datagen.flow_from_directory(
    test_dir,
    target_size=(150,150),
    batch_size=50,
    class_mode='binary',
    shuffle=False
)

Found 5000 images belonging to 2 classes.


In [14]:
test_loss,test_accuracy=model.evaluate(test_gen,steps=len(test_gen))

print(test_loss)
print(test_accuracy)

100/100 ━━━━━━━━━━━━━━━━━━━━ 7s 69ms/step - accuracy: 0.8564 - loss: 0.4573
0.45733189582824707
0.8564000129699707


In [15]:
probabilities=model.predict(test_gen)
probabilities

100/100 ━━━━━━━━━━━━━━━━━━━━ 11s 109ms/step


array([[4.0275150e-05],
       [2.8159246e-03],
       [5.7606574e-04],
       ...,
       [9.9842864e-01],
       [9.2540783e-01],
       [8.4578115e-01]], dtype=float32)

In [16]:
predicted_class=(probabilities>0.5).astype(int).squeeze()
predicted_class

array([0, 0, 0, ..., 1, 1, 1])

In [19]:
from sklearn.metrics import confusion_matrix

true_class = test_gen.classes

cm = confusion_matrix(true_class, predicted_class)

print(cm)

[[2219  281]
 [ 437 2063]]


In [20]:
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np
test_image="/content/dogsvscats/test/cats/cat.10001.jpg"
img=load_img(test_image,target_size=(150,150))
img_array=img_to_array(img)
img_array=np.expand_dims(img_array,axis=0)
img_array/=255.
img_array.shape

(1, 150, 150, 3)

In [21]:
model.predict(img_array)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 882ms/step


array([[0.00057607]], dtype=float32)