In [1]:
import numpy as np

In [7]:
image=np.array([
    [1,2,3,0,1],
    [0,1,2,3,2],
    [3,0,1,2,1],
    [2,3,1,0,0],
    [1,2,0,1,2]
])
kernel=np.array([
    [0,1,0],
    [1,-4,1],
    [0,1,0]
])
def conv(image,kernel):
    image_h,image_w=image.shape
    kernel_h,kernel_w=kernel.shape
    output_h=image_h-kernel_h+1
    output_w=image_w-kernel_w+1
    output_matrix=np.zeros((output_h,output_w))
    
    for i in range(output_h):
        for j in range(output_w):
            region=image[i:i+kernel_h,j:j+kernel_w]
            output_matrix[i,j]=np.sum(region*kernel)
            
    return output_matrix


output=conv(image,kernel)
        
output

array([[ 0.,  0., -6.],
       [ 8.,  1., -3.],
       [-7.,  0.,  4.]])

In [5]:
# padding

def padding(image,padd):
    output_h,output_w=image.shape
    output=np.zeros((output_h+padd*2,output_w+padd*2))
    
    for i in range(output_h):
        for j in range(output_w):
            output[i+padd,j+padd]=image[i,j]
            
    return output

output1=padding(image,1)

print(output1)

# numpy.pad

np.pad(image,1,mode='constant',constant_values=0)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 0. 1. 0.]
 [0. 0. 1. 2. 3. 2. 0.]
 [0. 3. 0. 1. 2. 1. 0.]
 [0. 2. 3. 1. 0. 0. 0.]
 [0. 1. 2. 0. 1. 2. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0, 1, 0],
       [0, 0, 1, 2, 3, 2, 0],
       [0, 3, 0, 1, 2, 1, 0],
       [0, 2, 3, 1, 0, 0, 0],
       [0, 1, 2, 0, 1, 2, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [ ]:
# stride

def stride(image,stride):
    

In [12]:
def conv_with_padding_stride(image,kernel,padd,stride):
    output_h,output_w=image.shape
    output=np.zeros((output_h+padd*2,output_w+padd*2))
    
    for i in range(output_h):
        for j in range(output_w):
            output[i+padd,j+padd]=image[i,j]
            
    output_h=(output_h-kernel.shape[0]+2*padd)//stride+1
    output_w=(output_w-kernel.shape[1]+2*padd)//stride+1
    output_matrix=np.zeros((output_h,output_w))
    
    for i in range(0,output_h*stride,stride):
        for j in range(0,output_w*stride,stride):
            output_matrix[i//stride,j//stride]=np.sum(output[i:i+kernel.shape[0],j:j+kernel.shape[1]]*kernel)
    
    return output_matrix
kernel=np.array([
    [0,1,0],
    [1,-4,1],
    [0,1,0]
])

output=conv_with_padding_stride(image,kernel,1,1)
    
output    
    


array([[ -2.,  -3.,  -8.,   7.,  -2.],
       [  5.,   0.,   0.,  -6.,  -3.],
       [-10.,   8.,   1.,  -3.,   0.],
       [ -1.,  -7.,   0.,   4.,   3.],
       [  0.,  -4.,   4.,  -2.,  -7.]])